### ISSUE TITLE
[Not a bug, but a suggestion] show live preview on the cam controller screen?

### ISSUE THREAD

**Issue by walterjunjun** [RF-Nelson/open-source-selfie-stick#2]
Hi Richard,

I was test your project and found it could be more useful if the cam controller could show live preview on the screen before we tap to capture a photo.
Do you think it is possible (easy) to add this functioning? Actually, I am also learning from your code. If you could give some suggestion, I could try to add this as a beginner.

Thanks,

Walter

**Comment by RF-Nelson** [comment]
Hi Walter!

This is definitely possible, but it may be difficult. I hope to add this feature sometime this year. You could try looking at [this](https://github.com/pj4533/AVCaptureMultipeerVideoDataOutput) GitHub repo that accomplishes this task, but unfortunately it is programmed in Objective-C and not Swift, so some translation will be necessary.

I also hope to create a tutorial to show beginners how I made this app. Perhaps when that is completed you might be in a better position to try adding this functionality yourself, and then you could submit a pull request.

Thank you for your interest, and I hope you have a nice day.

**Comment by walterjunjun** [comment]
Hi Richard,

Thanks for your information. I will follow your suggestion to have a try.
Really appreciate your willingness to share your code and experience with
beginners. The tutorial in future will be great!

Hope you also have a nice day.

Walter

On Tue, Mar 1, 2016 at 3:50 PM, Richard Nelson notifications@github.com
wrote:

> Hi Walter!
> 
> This is definitely possible, but it may be difficult. I hope to add this
> feature sometime this year. You could try looking at this
> https://github.com/pj4533/AVCaptureMultipeerVideoDataOutput GitHub repo
> that accomplishes this task, but unfortunately it is programmed in
> Objective-C and not Swift, so some translation will be necessary.
> 
> I also hope to create a tutorial to show beginners how I made this app.
> Perhaps when that is completed you might be in a better position to try
> adding this functionality yourself, and then you could submit a pull
> request.
> 
> Thank you for your interest, and I hope you have a nice day.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RF-Nelson/open-source-selfie-stick/issues/2#issuecomment-190921816
> .

## 

Wenjun (Walter) Kou
PhD student at Northwestern University, US
Theoretical and Applied Mechanics Program

**Comment by RF-Nelson** [comment]
Hi Walter,

I finally got around to writing that tutorial. Check it out: https://gist.github.com/RF-Nelson/8a3e6319b0607cf6b181ae4ee00f6c4c

Hope you're doing well

**Comment by walterjunjun** [comment]
Thanks for your effort. It is very helpful.
